name: frontend

on:
    push:
        branchs:
            - main
defaults:
    run:
        working-directory: myapp/frontend

jobs:
    deploy:
        runs-on: ubuntu:latest
        steps:
            - uses: actions/checkout@v3
            - run: aws s3 sync . s3://github-actions-tantan --exact-timestamps --region ap-northeast-1
            